//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.6
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub d7e72be2-215f-4404-abc3-ff9743fae514 aws-my-sample-app-android-v0.6";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
        Regions.US_EAST_1;
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:6d54f99d-7587-40d5-8a15-1fb02a6fafaa";
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "mpafrica-contentdelivery-mobilehub-2144746416";
    public static final String AMAZON_CLOUD_FRONT_DISTRIBUTION_DOMAIN =
        "doyvfpldm7c3l.cloudfront.net";
}
